---
title: "Fig3_panels"
output: html_document
date: "2025-12-16"
---
```{r figure_3a, include=FALSE, echo = FALSE}
coloh <- read.csv("/Volumes/Extreme SSD/Final_Figures_9_2022/Final Figures/Tables/fig3_a.csv")

rb1_lcn1 <- coloh %>% filter(BRCA2 == "gBRCA2_PV") %>% select(-BRCA2, -X)
rb1_lcn2 <- coloh %>% filter(BRCA2 == "gWT") %>% select(-BRCA2, -X)

n1 = length(unique(rb1_lcn1$sample))

### Median position by band
band_median <- rb1_lcn1 %>% 
  group_by(band) %>% 
  mutate(band_median = median(start, end, na.rm = TRUE)) %>%
  select(c(band, band_median)) %>%
  distinct(band, band_median, .keep_all = TRUE)

rb1_lcn1 <- rb1_lcn1 %>% 
  filter(lcn != "NA") %>% filter(lcn != "NF") %>%
  mutate(LCN = case_when(lcn == 0 ~ "LOH", TRUE ~ "No LOH")) %>%
  select(c(sample, band, LCN)) %>%
  distinct(sample, band, .keep_all = TRUE)

rb1_lcn1 <- rb1_lcn1 %>% group_by(band) %>% dplyr::mutate(n.group=length(band))
d1 <- rb1_lcn1 %>% group_by(band, LCN) %>% dplyr::summarise(n1 = length(LCN), gBRCA2 = sum(LCN=="LOH")/n.group[1]*100)

n2 = length(unique(rb1_lcn2$sample))

rb1_lcn2 <- rb1_lcn2 %>% 
  filter(lcn != "NA") %>% filter(lcn != "NF") %>%
  mutate(LCN = case_when(lcn == 0 ~ "LOH", TRUE ~ "No LOH")) %>%
  select(c(sample, band, LCN)) %>%
  distinct(sample, band, .keep_all = TRUE)

rb1_lcn2 <- rb1_lcn2 %>% group_by(band) %>% dplyr::mutate(n.group=length(band))
d2 <- rb1_lcn2 %>% group_by(band, LCN) %>% dplyr::summarise(n2 = length(LCN), gWT = -(sum(LCN=="LOH")/n.group[1]*100))

d = merge(d1, d2, by = c("band", "LCN"))

df = reshape2::melt(d, id.vars = c("band", "LCN"), measure.vars = c("gBRCA2", "gWT"))
df = merge(df, band_median, by = c("band"), all.x = T)

df_subset <- df %>% filter(band_median %in% (30863093:78197507))
df_subset$band_median <- as.factor(df_subset$band_median)

df_subset <- df_subset %>%
  mutate(
    highlight = ifelse(band_median %in% c(34656566, 46528600),
                       as.character(variable),
                       "Other")
  )

p <- ggplot(
  subset(df_subset, LCN == "LOH"),
  aes(x = band_median, y = value, fill = highlight, colour = highlight)
) +
  geom_col(width = 1, position = "identity") +
  scale_y_continuous(
    limits = c(-40, 100),
    breaks = seq(-40, 100, by = 20)
  ) +
  scale_fill_manual(
    values = c(
      "gWT" = "#02b26e",       
      "gBRCA2" = "#eb5299",
      "Other" = "grey80"
    )
  ) +
  scale_colour_manual(
    values = c(
      "gWT" = "#02b26e",
      "gBRCA2" = "#eb5299",
      "Other" = "grey80"
    )
  ) +
  ylab("Proportion of LOH (%)") +
  theme_gray() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(), 
    axis.title.x = element_blank(),
    axis.text.y = element_text(size = 15, colour = "black"),
    text = element_text(size = 14, colour = "black"),
    plot.title = element_text(size = 14, colour = "black"),
    legend.text = element_text(size = 14, colour = "black"),
    legend.title = element_blank()
  )

# Compare whether co-occurrence of RB1 and BRCA2 LOH is dependent on gBRCA2 status
coloh <- coloh %>% filter(hgnc %in% c("RB1", "BRCA2"))
coloh <- coloh %>% mutate(loh = case_when(lcn == "0" ~ "1", is.na(lcn) ~ "NA", lcn == "NF" ~ "NA", TRUE ~ "0"))
coloh.na <- coloh %>% filter(loh == "NA") %>% pull(sample)
coloh.e <- coloh %>% filter(sample %notin% coloh.na)
coloh.b2 <- coloh.e %>% filter(BRCA2 == "gBRCA2_PV") %>% select(sample, hgnc, loh) 
coloh.b2 <- distinct(coloh.b2)
coloh.b2 <- coloh.b2 %>% pivot_wider(names_from = hgnc, values_from = loh)
coloh.b2 <- coloh.b2 %>% mutate(BRCA2 = as.numeric(BRCA2)) %>% mutate(RB1 = as.numeric(RB1)) %>% mutate(coloh = BRCA2 + RB1)
coloh.b2 <- coloh.b2 %>% mutate(coloh = case_when(coloh == 2 ~ 1, TRUE ~ 0))
coloh.b2 <- coloh.b2 %>% mutate(GL = "B2")

coloh.wt <- coloh.e %>% filter(BRCA2 == "gWT") %>% select(sample, hgnc, loh) 
coloh.wt <- distinct(coloh.wt)
coloh.wt <- coloh.wt %>% pivot_wider(names_from = hgnc, values_from = loh)
coloh.wt <- coloh.wt %>% mutate(BRCA2 = as.numeric(BRCA2)) %>% mutate(RB1 = as.numeric(RB1)) %>% mutate(coloh = BRCA2 + RB1)
coloh.wt <- coloh.wt %>% mutate(coloh = case_when(coloh == 2 ~ 1, TRUE ~ 0))
coloh.wt <- coloh.wt %>% mutate(GL = "WT")

coloh.compare <- rbind(coloh.b2, coloh.wt)
fisher.exact(table(coloh.compare$GL, coloh.compare$coloh))

```

```{r fig_3bci, include=FALSE}
clin_t <- read_clip_tbl() # Need to get data from actual uploaded supplement 
cdk1 <- clin_t
colnames(cdk1) <- c("Sample.ID", "Patient.ID", "RB1.tcn", "RB1.lcn", "RB1.LOH", "rb1_ascn", "ET.partner", "Treatment.Regimen", "Reason.Stop", "Tx.Line", "PFS.event", "PFS.time.months", "fga", "wgd_bin", "os.event", "time1", "time2", "age.at.dx")

my_cols <- c("No_LOH" = "#3db54a", "LOH" = "#e95298")

#Fig3b
cdk_km_loh <- survfit(Surv(PFS.time.months, PFS.event) ~ RB1.LOH, data = cdk1)

cdk_loh.plot <- ggsurvplot(cdk_km_loh,
                        
                            risk.table= TRUE, tables.height = 0.20,
                            tables.theme = theme_cleantable(),
                            censor = TRUE,
                            break.time.by = 12,
                            fontsize = 3,
                            axes.offset = FALSE,
                            xlab = "Follow up time (mo)",
                         xlim = c(0,60))

cdk1 <- cdk1 %>% mutate(RB1.LOH = factor(RB1.LOH, levels = c("No_LOH", "LOH")))
summary(coxph(Surv(PFS.time.months, PFS.event) ~ RB1.LOH + ET.partner, data = cdk1))



# Fig3c 
os.km <- survfit(Surv(time1, time2, os.event) ~ RB1.LOH, data = cdk1)
os.km.plot <- ggsurvplot(os.km,
                           
                            risk.table= TRUE, tables.height = 0.20,
                            tables.theme = theme_cleantable(),
                            censor = TRUE,
                            break.time.by = 12,
                            fontsize = 3,
                            axes.offset = FALSE,
                            xlab = "Follow up time (mo)",
                         xlim = c(0,84))

summary(coxph(Surv(time1, time2, os.event) ~ ET.partner + RB1.LOH, data = cdk1))


cdk1 <- cdk1 %>% mutate(rb1_ascn = factor(rb1_ascn, levels = c("Heterozygous", "Other_LOH", "Het_loss")))
#OS - unadjusted by FGA, WGD
os.un <- coxph(Surv(time1, time2, os.event) ~ rb1_ascn + ET.partner, data = cdk1)
t.os.un <- tidy(os.un, exponentiate = TRUE, conf.int = TRUE) %>% filter(term %in% c("rb1_ascnOther_LOH", "rb1_ascnHet_loss")) %>% select(term, estimate, p.value, conf.low, conf.high) %>% mutate(analysis = "OS_univariate")

#OS - adjusted by FGA, WGD
os.adj <- coxph(Surv(time1, time2, os.event) ~ rb1_ascn + ET.partner + wgd_bin + fga, data = cdk1)
t.os.adj <- tidy(os.adj, exponentiate = TRUE, conf.int = TRUE) %>% filter(term %in% c("rb1_ascnOther_LOH", "rb1_ascnHet_loss")) %>% select(term, estimate, p.value, conf.low, conf.high) %>% mutate(analysis = "OS_multivariate")

#PFS - unadjusted by FGA, WGD
pfs.un <- coxph(Surv(PFS.time.months, PFS.event) ~ rb1_ascn + ET.partner, data = cdk1)
t.pfs.un <- tidy(pfs.un, exponentiate = TRUE, conf.int = TRUE) %>% filter(term %in% c("rb1_ascnOther_LOH", "rb1_ascnHet_loss")) %>% select(term, estimate, p.value, conf.low, conf.high) %>% mutate(analysis = "PFS_univariate")
#PFS - adjusted by FGA, WGD
pfs.adj <- coxph(Surv(PFS.time.months, PFS.event) ~ rb1_ascn + ET.partner+ wgd_bin + fga, data = cdk1)
t.pfs.adj <- tidy(pfs.adj, exponentiate = TRUE, conf.int = TRUE) %>% filter(term %in% c("rb1_ascnOther_LOH", "rb1_ascnHet_loss")) %>% select(term, estimate, p.value, conf.low, conf.high) %>% mutate(analysis = "PFS_multivariate")

ascn_outcomes_for_forest <- rbind(t.pfs.un, t.pfs.adj)
ascn_outcomes_for_forest <- rbind(ascn_outcomes_for_forest, t.os.un)
ascn_outcomes_for_forest <- rbind(ascn_outcomes_for_forest, t.os.adj)

```

```{r fig 3g, include = FALSE}
all.pw2.plus <- read_clip_tbl()
all.pw2.plus <- read.csv("pre_post...")

{get_type_fun = function(x) strsplit(x, ";")[[1]]

col_op = c("WT" = "#CCCCCC", "Het_loss" = brewer.pal(4, "BuPu")[3], "Other_LOH" = "magenta", "Heterozygous" = brewer.pal(4, "BuPu")[1],
           "Missense_driver" =  "darkgreen", "Splice_driver" = "darkorange1", "Truncating_driver" = "#001540", "Fusion" = "purple", "Amplification" = "red", "Deletion" = "blue")


alter_fun = list(
    background = function(x,y,w,h) {grid.rect(x,y,w,h, gp = gpar(fill = "white", col = NA))}, 
   WT = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
              gp = gpar(fill = col_op["WT"], col = NA))
   },
  Het_loss= function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
               gp = gpar(fill = col_op["Het_loss"], col = NA))
   },
  Other_LOH = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
              gp = gpar(fill = col_op["Other_LOH"], col = NA))
   },
  Heterozygous = function(x, y, w, h) {
    grid.rect(x, y,w*0.9, h*0.9,
             gp = gpar(fill = col_op["Heterozygous"], col = NA))
   },
   Amplification = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
              gp = gpar(fill = col_op["Amplification"], col = NA))
   },
    Deletion = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
              gp = gpar(fill = col_op["Deletion"], col = NA))
   },
   Missense_driver = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.33,
              gp = gpar(fill = col_op["Missense_driver"], col = NA))
   },
   Splice_driver = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.33,
              gp = gpar(fill = col_op["Splice_driver"], col = NA))
   },
   Truncating_driver = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.33,
              gp = gpar(fill = col_op["Truncating_driver"], col = NA))
   },
   Fusion = function(x, y, w, h) {
     grid.rect(x, y, w-unit(2, "pt"), h*0.33,
              gp = gpar(fill = col_op["Fusion"], col = NA))
  },
   acquired = function(x, y, w, h) {
    grid.rect(x, y, w, h,
              gp = gpar(fill = NA, lwd = 2))
   },
   Not_Tested = function(x,y,w,h) {
     grid.points(x,y,pch = "-")
   }
  
    )
  

heatmap_legend_param = list(title = "Variants (Annotated Drivers)", at = c("WT","Het_loss", "Other_LOH", "Heterozygous", "Missense_driver", "Splice_driver", "Truncating_driver",  "Fusion", "Amplification", "Deletion", "acquired"), 
                            labels = c("WT","Het Loss", "Other LOH", "Heterozygous", "Missense mutation (putative driver)", "Splice Site mutation (putative driver)", "Truncating mutation (putative driver)","Fusion (putative driver)", "Amplification", "Homozygous deletion", "Acquired on CDK4/6"), ncol = 3)

all.pw2.plus <- all.pw2.plus %>% 
  mutate(across(Post_RB1:Post_CCNE1, ~factor(.x, levels = c("Not Tested", "WT", "Deletion", "Amplification", "Fusion", "Splice_driver", "Missense_driver", "Truncating_driver", "Amplification;acquired", "Deletion;acquired", "Fusion;acquired", "Splice_driver;acquired", "Missense_driver;acquired", "Truncating_driver;acquired")))) 

all.pw2.plus <- all.pw2.plus %>% mutate(rb1_ascn = factor(rb1_ascn, levels = c("Heterozygous", "Other_LOH", "Het_loss")))

all.pw2.plus <- all.pw2.plus %>%
arrange(-as.numeric(rb1_ascn),
-as.numeric(Post_RB1), 
-as.numeric(Post_PTEN), 
-as.numeric(Post_AURKA), 
-as.numeric(Post_LATS2), 
-as.numeric(Post_YAP1),
-as.numeric(Post_FAT1), 
-as.numeric(Post_CCNE1))  

awp <- all.pw2.plus %>% select(Sample, rb1_ascn, Post_RB1, Post_PTEN, Post_AURKA, Post_LATS2, Post_YAP1, Post_FAT1, Post_CCNE1)

abt.plus <- t(awp)
colnames(abt.plus) <- abt.plus[1,]
abt.plus <- abt.plus[-1,]
samp.order <- colnames(abt.plus)

ann.op.plus <- all.pw2.plus %>% pull(rb1_ascn)

col.ann <- list(rb1_ascn = c("Het_loss" = brewer.pal(4, "BuPu")[3], "Other_LOH" = "magenta", "Heterozygous" = brewer.pal(4, "BuPu")[1]))

ht_opt$COLUMN_ANNO_PADDING = unit(8, "mm")
op_pre_post <- oncoPrint(as.matrix(abt.plus), alter_fun = alter_fun, col = col_op, column_order = samp.order, row_names_side = "left", pct_side = "right", row_names_gp = gpar(fontsize = 12), 
                         
                       column_split = all.pw2.plus$rb1_ascn, column_gap = unit(6, "mm"),  
                        #row_split = row_cuts, 
                         row_gap = unit(3, "mm"), 
                         #row_gap = unit(3, "mm"),
                         row_order = row.names(abt.plus),
                         right_annotation = NULL, show_pct = FALSE, 
                         column_title = "Pre-post CDK4/6 samples ", 
                         heatmap_legend_param = heatmap_legend_param,
                         alter_fun_is_vectorized = TRUE)
pdf(file = "heatmap_ascn.pdf", width = 50, height = 8)
draw(op_pre_post, heatmap_legend_side = "bottom", annotation_legend_side = "bottom")
dev.off()
```

```{r figure_3k, include = FALSE, echo = FALSE}
rb1.con.hr <- read.csv("~/Desktop/rebuttal_TSG_general/Re-analysis/Supplementary_Tables/Supp_S8d.csv")
colnames(rb1.con.hr) <- c("Patient.ID", "Alteration", "B2")
rb1.con.hr <- rb1.con.hr %>% mutate(HRD_cons = case_when(Alteration %in% c("Deletion <= 25nt", "Fusion") ~ 1, TRUE ~ 0))

fisher.exact(table(rb1.con.hr$B2, rb1.con.hr$HRD_cons))

colnames(rb1.con.hr)[2] <- "Alteration"
rb1.con.b2 <- rb1.con.hr %>% filter(B2 == "gBRCA2")
rb1.con.wt <- rb1.con.hr %>% filter(B2 == "WT")

con_freq_b2 <- as.data.frame(table(rb1.con.b2$Alteration))
colnames(con_freq_b2) <- c("Alteration", "numb")
con_freq_b2 <- con_freq_b2 %>% mutate(prop = numb/sum(numb)) 
con_freq_b2 <- con_freq_b2 %>% arrange(desc(Alteration))

con_freq_wt <- as.data.frame(table(rb1.con.wt$Alteration))
colnames(con_freq_wt) <- c("Alteration", "numb")
con_freq_wt <- con_freq_wt %>% mutate(prop = numb/sum(numb))

con_freq_b2 <- con_freq_b2 %>% mutate(Alteration = case_when(Alteration == "Deletion <= 25nt" ~ "A.Short Deletion", Alteration == "Fusion" ~ "B.SV", TRUE ~ Alteration))
con_freq_wt <- con_freq_wt %>% mutate(Alteration = case_when(Alteration == "Deletion <= 25nt" ~ "A.Short Deletion", Alteration == "Fusion" ~ "B.SV", TRUE ~ Alteration))


my_cols <- c(
  "A.Short Deletion" = "#bc6ead",
  "B.SV" = "#e4b4d3",
  "Deletion > 25 nt" = "#9e6127",
  "Homozygous Deletion" = "#5095cd",
  "Insertion" = "#fec65d",
  "Missense" = "#7fc67c"
)

con_freq_wt <- con_freq_wt %>% arrange(Alteration)
pie_wt <-  pie(con_freq_wt$prop, col = my_cols, labels = con_freq_wt$Alteration)

my_cols_b2 <- c(
  "A.Short Deletion" = "#bc6ead",
  "B.SV" = "#e4b4d3",
  "Homozygous Deletion" = "#5095cd",
  "Missense" = "#7fc67c"
)
con_freq_b2 <- con_freq_b2 %>% arrange(Alteration)

pie_b2 <- pie(con_freq_b2$prop, col = my_cols_b2, labels = con_freq_b2$Alteration)

#The plots appear to be conssistent, but the analysis leads to slightly different results: 

```

```{r figure_3l, include = FALSE, echo = FALSE}
cdk_b2_all <- read_clip_tbl()
colnames(cdk_b2_all) <- c("Patient.ID", "Tx.Line", "time.months", "event", "ET_partner", "B2", "cohort", "RB1_LOH")

cdk_b1 <- cdk_b2_all %>% filter(Tx.Line == 1)
cdk_b1 <- cdk_b1 %>% mutate(RB1_LOH = factor(RB1_LOH, levels = c("no_LOH", "RB1_LOH", "B2")))
summary(coxph(Surv(time.months, event) ~ RB1_LOH + ET_partner, data = cdk_b1))

cdk_tri_loh <- survfit(Surv(time.months, event) ~ RB1_LOH, data = cdk_b1)

cdk_tri.plot <- ggsurvplot(cdk_tri_loh,
                           palette = c("#32b34b","#af4e9d", "#e95298"),
risk.table= TRUE, tables.height = 0.20,
tables.theme = theme_cleantable(),
censor = TRUE,
break.time.by = 12,
fontsize = 3,
axes.offset = FALSE,
xlab = "Follow up time (mo)",
xlim = c(0,72))
```

```{r figure_3m, include = FALSE, echo = FALSE}

```

