---
title: "Germline-somatic interaction - Figure 1"
author:
  - name: Anton Safonov, Luca Boscolo Bielo, David N Brown
output:
  html_document:
    theme: cerulean
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
library('BSgenome.Hsapiens.UCSC.hg19')
library('ComplexHeatmap')
library('copynumber')
library('data.table')
library('doMC')
library('dplyr')
library('exact2x2')
library('foreach')
library('fuzzyjoin')
library('gdata')
library('GenomicRanges')
library('ggforce')
library('ggnomics')
library('ggplot2')
library('gplots')
library('ggrepel')
library('ggsignif')
library('gridExtra')
library('Gviz')
library('htmltools')
library('jsonlite')
library('knitr')
library('logistf')
library('lubridate')
library('maftools')
library('magrittr')
library('mime')
library('pander')
library('parallel')
library('RColorBrewer')
library('readr')
library('reshape2')
library('superheat')
library('survival')
library('survminer')
library('tidyr')
library('tidyverse')
library('viridis')

registerDoMC(8)

'%notin%' <- function(x,y) {
	!(x %in% y)
}

'colMax' <- function(data) {
	sapply(data, max, na.rm = TRUE)
}

'numextract' <- function(string) {
	str_extract(string, "\\-*\\d+\\.*\\d*")
}

'tabf' <- function(x, y, i) {
	z = c(colnames(x)[i+4], 
	      exp(y$coefficients[[2]]),
	      exp(y$ci.lower[[2]]),
	      exp(y$ci.upper[[2]]),
	      y$prob[[2]],
	      sum(x[, i+4])/dim(x)[1]*100,
	      sum(x[x$GL == 1,i+4])/dim(x[x$GL == 1, ])[1]*100,
	      sum(x[x$GL == 1,i+4]),
	      exp(logistf(GL ~ x[,i+4], data=x)$coefficients[[2]]),
	      logistf(GL ~ x[,i+4], data=x)$prob[[2]])
	return(invisible(z))
}
```

```{r create_gl_arrays, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.ann.w = readr::read_csv(file = "../data/Supp_Fig1a_ANON.csv.gz", col_names = TRUE, col_types = cols(.default = col_character())) %>%
	  readr::type_convert() %>%
	  dplyr::select(-`X1`, -X) %>%
	  dplyr::rename(Patient.ID = Anonymized.ID) %>%
	  dplyr::mutate(GL_WT = as.integer(rowSums(across(c(GL_BRCA1, GL_BRCA2, GL_CHEK2, GL_ATM, GL_PALB2)), na.rm = TRUE) == 0)) %>%
	  dplyr::relocate(GL_WT, .after = GL_PALB2)

d.brca1 = d.ann.w %>%
	  dplyr::filter(GL_BRCA1 == 1 | GL_WT == 1) %>%
	  dplyr::select(-GL_BRCA2, -GL_CHEK2, -GL_ATM, -GL_PALB2, -BIALLELIC_BRCA2, -BIALLELIC_CHEK2, -BIALLELIC_ATM, -BIALLELIC_PALB2)
d.brca2 = d.ann.w %>%
	  dplyr::filter(GL_BRCA2 == 1 | GL_WT == 1) %>%
	  dplyr::select(-GL_BRCA1, -GL_CHEK2, -GL_ATM, -GL_PALB2, -BIALLELIC_BRCA1, -BIALLELIC_CHEK2, -BIALLELIC_ATM, -BIALLELIC_PALB2)
d.chek2 = d.ann.w %>%
	  dplyr::filter(GL_CHEK2 == 1 | GL_WT == 1) %>%
	  dplyr::select(-GL_BRCA1, -GL_BRCA2, -GL_ATM, -GL_PALB2, -BIALLELIC_BRCA1, -BIALLELIC_BRCA2, -BIALLELIC_ATM, -BIALLELIC_PALB2)
d.palb2 = d.ann.w %>%
	  dplyr::filter(GL_PALB2 == 1 | GL_WT == 1) %>%
	  dplyr::select(-GL_BRCA1, -GL_BRCA2, -GL_CHEK2, -GL_ATM, -BIALLELIC_BRCA1, -BIALLELIC_BRCA2, -BIALLELIC_CHEK2, -BIALLELIC_ATM)
d.atm = d.ann.w %>%
	dplyr::filter(GL_ATM == 1 | GL_WT == 1) %>%
	dplyr::select(-GL_BRCA1, -GL_BRCA2, -GL_CHEK2, -GL_PALB2, -BIALLELIC_BRCA1, -BIALLELIC_BRCA2, -BIALLELIC_CHEK2, -BIALLELIC_PALB2)

loh.brca1 = d.brca1 %>%
	    dplyr::filter(BIALLELIC_BRCA1 == "Yes") %>%
	    dplyr::pull(Patient.ID)
noloh.brca1 = d.brca1 %>%
	      dplyr::filter(BIALLELIC_BRCA1 == "No") %>%
	      dplyr::pull(Patient.ID)

loh.brca2 = d.brca2 %>%
	    dplyr::filter(BIALLELIC_BRCA2 == "Yes") %>%
	    dplyr::pull(Patient.ID)
noloh.brca2 = d.brca2 %>%
	      dplyr::filter(BIALLELIC_BRCA2 == "No") %>%
	      dplyr::pull(Patient.ID)

loh.chek2 = d.chek2 %>%
	    dplyr::filter(BIALLELIC_CHEK2 == "Yes") %>%
	    dplyr::pull(Patient.ID)
noloh.chek2 = d.chek2 %>%
	      dplyr::filter(BIALLELIC_CHEK2 == "No") %>%
	      dplyr::pull(Patient.ID)

loh.atm = d.atm %>%
	  dplyr::filter(BIALLELIC_ATM == "Yes") %>%
	  dplyr::pull(Patient.ID)
noloh.atm = d.atm %>%
	    dplyr::filter(BIALLELIC_ATM == "No") %>%
	    dplyr::pull(Patient.ID)

loh.palb2 = d.palb2 %>%
	    dplyr::filter(BIALLELIC_PALB2 == "Yes") %>%
	    dplyr::pull(Patient.ID)
noloh.palb2 = d.palb2 %>%
	      dplyr::filter(BIALLELIC_PALB2 == "No") %>%
	      dplyr::pull(Patient.ID)

d.brca1 = d.brca1 %>%
	  dplyr::select(-GL_WT,-BIALLELIC_BRCA1) %>%
	  dplyr::rename(GL = GL_BRCA1)
d.brca2 = d.brca2 %>%
	  dplyr::select(-GL_WT,-BIALLELIC_BRCA2) %>%
	  dplyr::rename(GL = GL_BRCA2)
d.chek2 = d.chek2 %>%
	  dplyr::select(-GL_WT,-BIALLELIC_CHEK2) %>%
	  dplyr::rename(GL = GL_CHEK2)
d.palb2 = d.palb2 %>%
	  dplyr::select(-GL_WT,-BIALLELIC_PALB2) %>%
	  dplyr::rename(GL = GL_PALB2)
d.atm = d.atm %>%
	dplyr::select(-GL_WT,-BIALLELIC_ATM) %>%
	dplyr::rename(GL = GL_ATM)
```

<!-- BRCA2 -->

```{r brca2_log_reg, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = as.data.frame(d.brca2)
df.all.n = df.all[,-c(1:4)] 

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}

df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	#logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca2 = sm.log.results.c
```

```{r brca2_log_reg_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca2 %>%
	 dplyr::filter(Receptor.Status == "HR+/HER2-")
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca2.er = sm.log.results.c
```

```{r brca2_log_reg_tn, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca2 %>%
	 dplyr::filter(Receptor.Status == "TNBC")
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca2.tn = sm.log.results.c
```

```{r brca2_log_reg_loh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.brca2.bi = d.brca2 %>%
	     dplyr::filter(Patient.ID %notin% noloh.brca2)
d.brca2.uni = d.brca2 %>%
	      dplyr::filter(Patient.ID %notin% loh.brca2)

df.all = d.brca2.bi
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca2.bi = sm.log.results.c
```

```{r brca2_log_reg_noloh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca2.uni
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11)
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
  	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca2.uni = sm.log.results.c
```

```{r brca2_log_reg_loh_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.brca2.bi.er = d.brca2 %>%
		dplyr::filter(Patient.ID %notin% noloh.brca2) %>%
		dplyr::filter(Receptor.Status == "HR+/HER2-")
d.brca2.uni.er = d.brca2 %>%
		 dplyr::filter(Patient.ID %notin% loh.brca2) %>%
		 dplyr::filter(Receptor.Status == "HR+/HER2-")

df.all = d.brca2.bi.er
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
}
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1: num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
  	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   	q.value < 0.10 ~ "Yes",
			   	TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca2.bi.er = sm.log.results.c
```

```{r brca2_log_reg_noloh_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca2.uni.er
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
  	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca2.uni.er = sm.log.results.c
```

```{r brca2_log_reg_loh_tn, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.brca2.bi.tn = d.brca2 %>%
		dplyr::filter(Patient.ID %notin% noloh.brca2) %>%
		dplyr::filter(Receptor.Status == "TNBC")
d.brca2.uni.tn = d.brca2 %>%
		 dplyr::filter(Patient.ID %notin% loh.brca2) %>%
		 dplyr::filter(Receptor.Status == "TNBC")

df.all = d.brca2.bi.tn
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
  	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca2.bi.tn = sm.log.results.c
```

```{r brca2_log_reg_noloh_tn, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca2.uni.tn
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11)
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
  	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca2.uni.tn = sm.log.results.c
```

<!-- BRCA1 -->

```{r brca1_log_reg, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca1
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2] 
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca1 = sm.log.results.c
```

```{r brca1_log_reg_tn, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca1 %>%
	 dplyr::filter(Receptor.Status == "TNBC")
d.brca1.tn = df.all
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])]
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2] 
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca1.tn = sm.log.results.c
```

```{r brca1_log_reg_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca1 %>%
	 dplyr::filter(Receptor.Status == "HR+/HER2-")
d.brca1.er = d.brca1 %>%
	     dplyr::filter(Receptor.Status == "HR+/HER2-")

df.all.n = df.all[,-c(1:4)]
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2] 
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca1.er = sm.log.results.c
```

```{r brca1_log_reg_loh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.brca1.bi = d.brca1 %>%
	     dplyr::filter(Patient.ID %notin% noloh.brca1)
d.brca1.uni = d.brca1 %>%
	      dplyr::filter(Patient.ID %notin% loh.brca1)

df.all = d.brca1.bi
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca1.bi = sm.log.results.c
```

```{r brca1_log_reg_noloh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca1.uni
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res 

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   readr::type_convert()

lr.results.brca1.uni = sm.log.results.c
```

```{r brca1_log_reg_loh_tn, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.brca1.bi.tn = d.brca1 %>%
		dplyr::filter(Patient.ID %notin% noloh.brca1) %>%
		dplyr::filter(Receptor.Status == "TNBC")
d.brca1.uni.tn = d.brca1 %>%
		 dplyr::filter(Patient.ID %notin% loh.brca1) %>%
		 dplyr::filter(Receptor.Status == "TNBC")

df.all = d.brca1.bi.tn
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res 

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.brca1.bi.tn = sm.log.results.c
```

```{r brca1_log_reg_noloh_tn, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca1.uni.tn
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11)
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	# logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res 

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.brca1.uni.tn = sm.log.results.c
```

```{r brca1_log_reg_loh_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.brca1.bi.er = d.brca1 %>%
		dplyr::filter(Patient.ID %notin% noloh.brca1) %>%
		dplyr::filter(Receptor.Status == "HR+/HER2-")
d.brca1.uni.er = d.brca1 %>%
		 dplyr::filter(Patient.ID %notin% loh.brca1) %>%
		 dplyr::filter(Receptor.Status == "HR+/HER2-")

df.all = d.brca1.bi.er
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	# logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res 

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.brca1.bi.er = sm.log.results.c
```

```{r brca1_log_reg_noloh_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.brca1.uni.er
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res 

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.brca1.uni.er = sm.log.results.c
```

<!-- CHEK2 -->

```{r chek2_log_reg, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.chek2
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No")) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.chek2 = sm.log.results.c
```

```{r chek2_log_reg_loh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.chek2.bi = d.chek2 %>%
	     dplyr::filter(Patient.ID %notin% noloh.chek2)
d.chek2.uni = d.chek2 %>%
	      dplyr::filter(Patient.ID %notin% loh.chek2)

df.all = d.chek2.bi
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])]
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No")) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.chek2.bi = sm.log.results.c
```

```{r chek2_log_reg_noloh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.chek2.uni
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])]
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No")) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.chek2.uni = sm.log.results.c
```

```{r chek2_log_reg_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.chek2 %>%
	 dplyr::filter(Receptor.Status == "HR+/HER2-")
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.2*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No")) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.chek2.er = sm.log.results.c
```

```{r chek2_log_reg_er_loh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.chek2.bi = d.chek2 %>%
	     dplyr::filter(Patient.ID %notin% noloh.chek2)
d.chek2.uni = d.chek2 %>%
	      dplyr::filter(Patient.ID %notin% loh.chek2)

df.all = d.chek2.uni %>%
	 dplyr::filter(Receptor.Status == "HR+/HER2-")
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.2*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No")) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.chek2.uni.er = sm.log.results.c
```

```{r chek2_log_reg_er_noloh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.chek2.bi %>%
	 dplyr::filter(Receptor.Status == "HR+/HER2-")
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.2*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No")) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.chek2.bi.er = sm.log.results.c
```

<!-- ATM -->

```{r atm_log_reg, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.atm
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.atm = sm.log.results.c
```

```{r atm_log_reg_loh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.atm.bi = d.atm %>%
	   dplyr::filter(Patient.ID %notin% noloh.atm)
df.all = d.atm.bi
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11)
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.atm.bi = sm.log.results.c
```

```{r atm_log_reg_noloh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.atm.uni = d.atm %>%
	    dplyr::filter(Patient.ID %notin% loh.atm)
df.all = d.atm.uni
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.atm.uni = sm.log.results.c
```

```{r atm_log_reg_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.atm %>%
	 dplyr::filter(Receptor.Status == "HR+/HER2-")
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.atm.er = sm.log.results.c
```

```{r atm_log_reg_loh_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.atm.bi.er = d.atm %>%
	      dplyr::filter(Patient.ID %notin% noloh.atm) %>%
	      dplyr::filter(Receptor.Status == "HR+/HER2-")
d.atm.uni.er = d.atm %>%
	       dplyr::filter(Patient.ID %notin% loh.atm) %>%
	       dplyr::filter(Receptor.Status == "HR+/HER2-")
                                 
df.all = d.atm.bi.er
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])] 
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.atm.bi.er = sm.log.results.c
```

```{r atm_log_reg_noloh_er, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.atm.uni.er
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])]
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.atm.uni.er = sm.log.results.c
```

<!-- PALB2 -->

```{r palb2_log_reg, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.palb2
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])]
df.all = data.frame(df.all[,c(1:4)], df.all.n)
#df.all = df.all %>% select(-palb2)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 11) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic.Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq.overall", "freq.GL", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.brca2.gene = sm.log.results.c %>%
		       dplyr::filter(p.value < 0.05 | freq.overall > 7)
actual.sig.label = sm.log.results.c %>%
		   dplyr::filter(p.value < 0.05)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.palb2 = sm.log.results.c
```

```{r palb2_log_reg_loh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
d.palb2.bi = d.palb2 %>%
	     dplyr::filter(Patient.ID %notin% noloh.palb2)
d.palb2.uni = d.palb2 %>%
	      dplyr::filter(Patient.ID %notin% loh.palb2)

df.all = d.palb2.bi
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])]
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 10) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.palb2.bi = sm.log.results.c %>%
		     dplyr::filter(p.value < 0.05 | freq > 7)
sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))


lr.results.palb2.bi = sm.log.results.c
```

```{r palb2_log_reg_noloh, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
df.all = d.palb2.uni
df.all.n = df.all[,-c(1:4)] 
df.all.n = as.data.frame(df.all.n)

for (i in 1:dim(df.all.n)[2]) {
	df.all.n[,i] = as.numeric(as.character(df.all.n[,i]))
}
df.all.n = df.all.n[,which(colSums(df.all.n) > 0.02*dim(df.all.n)[1])]
df.all = data.frame(df.all[,c(1:4)], df.all.n)

num.genes = dim(df.all.n)[2]
sm.log.results.c = matrix(0, num.genes, 10) 
sm.log.results.c = data.frame(sm.log.results.c)
colnames(sm.log.results.c) = c("Somatic Variant", "OR", "Conf.Int.1", "Conf.Int.2", "p.value", "q.value", "freq", "num.coaltered.with.GL", "OR.univariate", "p.value.univariate")

res = foreach (i=1:num.genes) %dopar% {
	logx = logistf(GL ~ df.all[,i+4] + Receptor.Status + Sample.Type, pl = FALSE, data=df.all)
	res = tabf(x = df.all, y = logx, i = i)
	return(res)
} %>%
do.call(rbind, .)
sm.log.results.c[,-6] = res

sig.label.palb2.uni = sm.log.results.c %>%
		      dplyr::filter(p.value < 0.05 | freq > 7)

sm.log.results.c$q.value = p.adjust(sm.log.results.c$p.value, method = "BH")
sm.log.results.c = sm.log.results.c[order(sm.log.results.c$p.value),]
sm.log.results.c = sm.log.results.c %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant))

lr.results.palb2.uni = sm.log.results.c
```

<!-- Figure 1b-d -->

```{r, eval = TRUE, echo = FALSE, message = FALSE, include = TRUE, fig.align = 'left', fig.height = 8, fig.width = 8, fig.cap = '<br/>**Figure 1b-d:** Volcano plots of enrichment analysis of gATM (top-left). Similar to gATM, but depicting comparison of gBRCA1 (top-right). Similar to gATM, but depicting comparison of gBRCA2 (bottom-left). Similar to gBRCA2 using a subset of HR+/HER2- tumors (bottom-right)'}

### ATM
sm.log.results.c = lr.results.atm %>%
		   tidyr::as_tibble() %>%
		   readr::type_convert() %>%
		   dplyr::rename(Somatic.Mutation = Somatic.Variant) %>%
		   dplyr::mutate(Somatic.Mutation = ifelse(Somatic.Mutation %in% c('CCND1', 'FGF4', 'FGF19', 'FGF3'), "11q13", Somatic.Mutation)) %>%
		   dplyr::group_by(Somatic.Mutation) %>%
		   dplyr::summarise(OR = mean(OR),
				    Conf.Int.1 = mean(Conf.Int.1),
				    Conf.Int.2 = mean(Conf.Int.2),
				    p.value = mean(p.value),
				    q.value = mean(q.value),
				    freq = mean(freq.overall),
				    num.coaltered.with.GL = mean(num.coaltered.with.GL),
				    OR.univariate = mean(OR.univariate),
				    .groups = "drop") %>%
		   dplyr::arrange(p.value) %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant)) %>%
		   dplyr::mutate(log2OR = log2(OR)) %>%
		   dplyr::relocate(log2OR, .after = OR) %>%
		   dplyr::mutate(Somatic.Mutation = case_when(
			   		q.value < 0.1 ~ Somatic.Mutation, 
			   		Somatic.Mutation == 'RB1' ~ Somatic.Mutation, 
			   		TRUE ~ "NA"
		   )) %>%
		   readr::type_convert()

sig.label = sm.log.results.c 

plot_atm = sig.label %>%
	   ggplot(mapping = aes(x = log2OR, y = -log10(q.value), color = Significant, size = freq)) +
	   geom_point(stat = "identity", alpha = 0.4) +
	   scale_size(range = c(1, 10), name = "Frequency (%)") + 
	   scale_color_manual(values = c("Yes" = "blue", "No" = "gray45")) +
	   scale_x_continuous(limits = c(-3.5, 3.5), 
			      breaks = c(-3, -2, -1, 0, 1, 2, 3)) +
	   scale_y_continuous(limits = c(0, 9),
			      breaks = seq(1, 9, 2)) +
	   xlab('') +
	   ylab(expression(-log[10]('q value'))) +
	   ggtitle(" ") +
	   geom_text_repel(data = sig.label,
			   mapping = aes(x = log2(OR), y = -log10(q.value), label = Somatic.Mutation),
			   size = 4, nudge_y = 0.6, color = "black") + 
	   geom_vline(xintercept = 0, color = "red") +
	   geom_hline(yintercept = -log10(0.1), linetype = "dashed") +
	   theme_bw() +
	   theme(axis.title.x = element_text(size = 18),
		 axis.title.y = element_text(size = 18),
		 axis.text.x = element_text(size = 16),
		 axis.text.y = element_text(size = 16),
		 plot.title = element_text(hjust = 0.5, size = 24),
		 plot.subtitle = element_text(hjust = 0.5, size = 18),
		 legend.position = 'none',
		 panel.grid.major = element_blank(),
		 panel.grid.minor = element_blank())

### BRCA2
sm.log.results.c = lr.results.brca2 %>% 
		   tidyr::as_tibble() %>%
		   readr::type_convert() %>%
		   dplyr::mutate(Somatic.Variant = ifelse(Somatic.Variant %in% c('CCND1', 'FGF4', 'FGF19', 'FGF3'), "11q13", Somatic.Variant)) %>%
		   dplyr::group_by(Somatic.Variant) %>%
		   dplyr::summarise(OR = mean(OR),
				    Conf.Int.1 = mean(Conf.Int.1),
				    Conf.Int.2 = mean(Conf.Int.2),
				    p.value = mean(p.value),
				    q.value = mean(q.value),
				    freq = mean(freq.overall),
				    num.coaltered.with.GL = mean(num.coaltered.with.GL),
				    OR.univariate = mean(OR.univariate),
				    .groups = "drop") %>%
		   dplyr::arrange(p.value) %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		    )) %>%
		    dplyr::mutate(Significant = as.factor(Significant)) %>%
		    dplyr::mutate(log2OR = log2(OR)) %>%
		    dplyr::relocate(log2OR, .after = OR) %>%
		    dplyr::mutate(Somatic.Variant = if_else(q.value < 0.1, Somatic.Variant, "NA")) %>%
		    readr::type_convert()

sig.label = sm.log.results.c

plot_brca2 = sig.label %>%
	     ggplot(mapping = aes(x = log2OR, y = -log10(q.value), color = Significant, size = freq)) +
	     geom_point(stat = "identity", alpha = 0.4) +
	     scale_size(range = c(1, 10), name="Frequency (%)") + 
	     scale_color_manual(values = c("Yes" = "blue", "No" = "gray45")) +
	     scale_x_continuous(limits = c(-3.5, 3.5), 
				breaks = c(-3, -2, -1, 0, 1, 2, 3)) +
	     scale_y_continuous(limits = c(0, 9), 
				breaks = seq(1, 9, 2)) +
  	     xlab(expression(log[2]('Odds ratio'))) +
	     ylab(expression(-log[10]('q value'))) +
	     ggtitle(" ") +
	     geom_text_repel(data = sig.label,
			     mapping = aes(x = log2(OR), y = -log10(q.value), label = Somatic.Variant),
			     size = 4, nudge_y = 0.6, color = "black") + 
	     geom_vline(xintercept = 0, color = "red") +
	     geom_hline(yintercept = -log10(0.1), linetype = "dashed") +
	     theme_bw() +
	     theme(axis.title.x = element_text(size = 18),
		   axis.title.y = element_text(size = 18),
		   axis.text.x = element_text(size = 16),
		   axis.text.y = element_text(size=16),
		   plot.title = element_text(hjust = 0.5, size = 24),
		   plot.subtitle = element_text(hjust = 0.5, size = 18),
		   legend.position  = 'none',
		   panel.grid.major = element_blank(),
		   panel.grid.minor = element_blank())

### BRCA1
sm.log.results.c = lr.results.brca1 %>%
		   tidyr::as_tibble() %>%
		   readr::type_convert() %>%
		   dplyr::rename(Somatic.Mutation = Somatic.Variant) %>%
		   dplyr::mutate(Somatic.Mutation = ifelse(Somatic.Mutation %in% c('CCND1', 'FGF4', 'FGF19', 'FGF3'), "11q13", Somatic.Mutation)) %>%
		   dplyr::group_by(Somatic.Mutation) %>%
		   dplyr::summarise(OR = mean(OR),
				    Conf.Int.1 = mean(Conf.Int.1),
				    Conf.Int.2 = mean(Conf.Int.2),
				    p.value = mean(p.value),
				    q.value = mean(q.value),
				    freq = mean(freq.overall),
				    num.coaltered.with.GL = mean(num.coaltered.with.GL),
				    OR.univariate = mean(OR.univariate),
				    .groups = "drop") %>%
		   dplyr::arrange(p.value) %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			    	TRUE ~ "No"
		    )) %>%
		    dplyr::mutate(Significant = as.factor(Significant)) %>%
		    dplyr::mutate(log2OR = log2(OR)) %>%
		    dplyr::relocate(log2OR, .after = OR) %>%
		    dplyr::mutate(Somatic.Mutation = case_when(
			    		q.value < 0.1 ~ Somatic.Mutation, 
			    		Somatic.Mutation == 'RB1' ~ Somatic.Mutation,
			    		TRUE ~ "NA"
		    )) %>%
		    readr::type_convert()

sig.label = sm.log.results.c 

plot_brca1 = sig.label %>%
	     ggplot(mapping = aes(x = log2OR, y = -log10(q.value), color = Significant, size = freq)) +
	     geom_point(stat = "identity", alpha = 0.4) +
	     scale_size(range = c(1, 10), name="Frequency (%)") + 
	     scale_color_manual(values = c("Yes" = "blue", "No" = "gray45")) +
	     scale_x_continuous(limits = c(-3.5, 3.5), 
				breaks = c(-3, -2, -1, 0, 1, 2, 3)) +
	     scale_y_continuous(limits = c(0, 9), 
				breaks = seq(1, 9, 2)) +
	     xlab('') +
	     ylab('') + 
	     ggtitle(" ") +
	     geom_text_repel(data = sig.label,
			     mapping = aes(x = log2(OR), y = -log10(q.value), label = Somatic.Mutation),
			     size = 4, nudge_y = 0.6, color = "black") + 
	     geom_vline(xintercept = 0, color = "red") +
	     geom_hline(yintercept = -log10(0.1), linetype = "dashed") +
	     theme_bw() +
	     theme(axis.title.x = element_text(size = 18),
		   axis.title.y = element_text(size=18),
		   axis.text.x = element_text(size = 16),
		   axis.text.y = element_text(size=16), 
		   plot.title = element_text(hjust = 0.5, size = 24),
		   plot.subtitle = element_text(hjust = 0.5, size = 18),
		   legend.position = 'none',
		   panel.grid.major = element_blank(),
		   panel.grid.minor = element_blank())

### BRCA2_ER
sm.log.results.c = lr.results.brca2.er %>%
		   tidyr::as_tibble() %>%
		   readr::type_convert() %>%
		   dplyr::mutate(Somatic.Variant = ifelse(Somatic.Variant %in% c('CCND1', 'FGF4', 'FGF19', 'FGF3'), "11q13", Somatic.Variant)) %>%
		   dplyr::group_by(Somatic.Variant) %>%
		   dplyr::summarise(OR = mean(OR),
				    Conf.Int.1 = mean(Conf.Int.1),
				    Conf.Int.2 = mean(Conf.Int.2),
				    p.value = mean(p.value),
				    q.value = mean(q.value),
				    freq = mean(freq.overall),
				    num.coaltered.with.GL = mean(num.coaltered.with.GL),
				    OR.univariate = mean(OR.univariate),
				    .groups = "drop") %>%
		   dplyr::arrange(p.value) %>%
		   dplyr::mutate(Significant = case_when(
			   		q.value < 0.10 ~ "Yes",
			   		TRUE ~ "No"
		   )) %>%
		   dplyr::mutate(Significant = as.factor(Significant)) %>%
		   dplyr::mutate(log2OR = log2(OR)) %>%
		   dplyr::relocate(log2OR, .after = OR) %>%
		   dplyr::mutate(Somatic.Variant = if_else(q.value < 0.1, Somatic.Variant, "NA")) %>%
		   readr::type_convert()

sig.label = sm.log.results.c 

plot_brca2_er = sig.label %>%
		ggplot(mapping = aes(x = log2OR, y = -log10(q.value), color = Significant, size = freq)) +
		geom_point(stat = "identity", alpha = 0.4) +
		scale_size(range = c(1, 10), name="Frequency (%)") + 
		scale_color_manual(values = c("Yes" = "blue", "No" = "gray45")) +
		scale_x_continuous(limits = c(-3.5, 3.5), 
				   breaks = c(-3, -2, -1, 0, 1, 2, 3)) +
		scale_y_continuous(limits = c(0, 9), 
				   breaks = seq(1, 9, 2)) +
		xlab(expression(log[2]('Odds ratio'))) +
		ylab('') + 
		ggtitle(" ") +
		geom_text_repel(data = sig.label,
				aes(x = log2(OR), y = -log10(q.value), label = Somatic.Variant),
				size = 4, nudge_y = 0.5, color = "black") + 
		geom_vline(xintercept = 0, color = "red") +
		geom_hline(yintercept = -log10(0.1), linetype = "dashed") +
		theme_bw() +
		theme(axis.title.x = element_text(size = 18),
		      axis.title.y = element_text(size = 18),
		      axis.text.x = element_text(size = 16),
		      axis.text.y = element_text(size = 16), 
		      plot.title = element_text(hjust = 0.5, size = 24),
		      plot.subtitle = element_text(hjust = 0.5, size = 18),
		      panel.grid.major = element_blank(),
		      panel.grid.minor = element_blank())

suppressWarnings(grid.arrange(plot_atm, plot_brca1, plot_brca2, plot_brca2_er, nrow = 2, ncol = 2, widths = c(1, 1)))
```

<br/>