---
title: "Germline-somatic interaction - Figure 2"
author:
  - name: Anton Safonov, Luca Boscolo Bielo, David N Brown
output:
  html_document:
    theme: cerulean
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r, eval = TRUE, echo = FALSE, results = 'hide', include = FALSE}
library('BSgenome.Hsapiens.UCSC.hg19')
library('ComplexHeatmap')
library('copynumber')
library('data.table')
library('doMC')
library('dplyr')
library('exact2x2')
library('foreach')
library('fuzzyjoin')
library('gdata')
library('GenomicRanges')
library('ggforce')
library('ggnomics')
library('ggplot2')
library('gplots')
library('ggrepel')
library('ggsignif')
library('gridExtra')
library('Gviz')
library('htmltools')
library('jsonlite')
library('knitr')
library('logistf')
library('lubridate')
library('maftools')
library('magrittr')
library('mime')
library('pander')
library('parallel')
library('RColorBrewer')
library('readr')
library('reshape2')
library('superheat')
library('survival')
library('survminer')
library('tidyr')
library('tidyverse')
library('viridis')

registerDoMC(8)

'%notin%' <- function(x,y) {
	!(x %in% y)
}

'colMax' <- function(data) {
	sapply(data, max, na.rm = TRUE)
}

'numextract' <- function(string) {
	str_extract(string, "\\-*\\d+\\.*\\d*")
}

'tabf' <- function(x, y, i) {
	z = c(colnames(x)[i+4], 
	      exp(y$coefficients[[2]]),
	      exp(y$ci.lower[[2]]),
	      exp(y$ci.upper[[2]]),
	      y$prob[[2]],
	      sum(x[, i+4])/dim(x)[1]*100,
	      sum(x[x$GL == 1,i+4])/dim(x[x$GL == 1, ])[1]*100,
	      sum(x[x$GL == 1,i+4]),
	      exp(logistf(GL ~ x[,i+4], data=x)$coefficients[[2]]),
	      logistf(GL ~ x[,i+4], data=x)$prob[[2]])
	return(invisible(z))
}
```

```{r figure_2ab, include=FALSE, echo = FALSE}
cdk_b2_all = readr::read_csv(file = "../data/Supp_Fig2ab_CDK46_PFS_ANON.csv.gz", col_names = TRUE, col_types = cols(.default = col_character())) %>%
	     readr::type_convert() %>%
	     dplyr::select(-X1) %>%
	     dplyr::distinct() %>%
	     dplyr::rename_all( function(x) { c("Patient.ID", "Tx.Line", "time.months", "event", "ET_partner", "B2", "cohort", "RB1_LOH") })

cdk_b2_all <- cdk_b2_all %>% mutate(Tx.Line = as.numeric(Tx.Line)) 
cdk_b2_1 <- cdk_b2_all %>% filter(Tx.Line == 1)
cdk_b2_all <- cdk_b2_all %>% mutate(Tx.Line.c = case_when(Tx.Line == 1 ~ "1", (Tx.Line > 1 & Tx.Line < 4) ~ "2to3", (Tx.Line > 3 & Tx.Line < 6) ~ "4to5", Tx.Line > 5 ~ "6+"))
cdk_b2_all <- cdk_b2_all %>% mutate(Tx.Line.c = factor(Tx.Line.c, levels = c("1", "2to3", "4to5", "6+")))

#Fig2a
cdk_b2.f1 <- survfit(Surv(time.months, event) ~ B2, data = cdk_b2_1, conf.type = "log-log")
cdk_b2.f1.plot <- ggsurvplot(cdk_b2.f1,
palette = c("#00B26E", "#F54782"),
risk.table = TRUE, tables.height = 0.20,
tables.theme = theme_cleantable(),
censor=TRUE,
break.time.by = 6,
fontsize=3,
axes.offset= FALSE,
xlab="Follow up Time (mo)",
xlim = c(0,78))

#Fig 2b
cdk_b2.fall <- survfit(Surv(time.months, event) ~ B2, data = cdk_b2_all, conf.type = "log-log")
cdk_b2.fall.plot <- ggsurvplot(cdk_b2.fall,
palette = c("#00B26E", "#F54782"),
risk.table = TRUE, tables.height = 0.20,
risk.table.font.size = 10,
tables.theme = theme_cleantable(),
censor=TRUE,
break.time.by = 6,
fontsize=3,
axes.offset= FALSE,
xlab="Follow up Time (mo)",
xlim = c(0,78))

#Analysis for Fig2a-b
summary(coxph(Surv(time.months, event) ~ B2 + ET_partner, data = cdk_b2_1))
summary(coxph(Surv(time.months, event) ~ B2 + ET_partner + Tx.Line.c, data = cdk_b2_all))

  
```

```{r figure_2d, include = FALSE, echo = FALSE}
all.lines <- read.csv("../data/Supp_Fig2d_swimmer_ANON.csv")

col_map <- c("cdk" = "#4271D6", 
             "parp" = "#00B26E",
             "bet" = "#F4F4F4")
  
all.lines <- all.lines %>% rename(Reason.Stop = Reason_Stop)
all.lines <- all.lines %>% rename(Best.Response = Best_Resposne)
all.lines <- all.lines %>% rename(Start.Date.norm = Deidentified_Start_Date)
all.lines <- all.lines %>% rename(End.Date.norm = Deidentified_End_Date)

swimmer_plot <- ggplot(all.lines, aes(y = index)) +
  
  scale_fill_manual(values = c(
    "cdk"  = "#f16b6c",
    "parp" = "#6d90ca"
  )) +
  
  theme_classic() +
  theme(legend.position = "none") +
  
  geom_rect(
    aes(
      xmin = Start.Date.norm,
      xmax = End.Date.norm,
      ymin = index - 0.3,
      ymax = index + 0.3,
      fill = Tx.Type
    ),
    linewidth = 0.2,
    color = "black"
  ) +
  
  geom_point(
    data = subset(all.lines,
                  Reason.Stop == "Disease Progression" &
                  Tx.Type %in% c("cdk", "parp")),
    aes(x = End.Date.norm, y = index),
    color = "black",
    shape = 18,
    size = 3.0
  ) +
  
  geom_point(
    data = subset(all.lines,
                  Reason.Stop %in% c("MD Preference", "Toxicity") &
                  Tx.Type %in% c("cdk", "parp")),
    aes(x = End.Date.norm, y = index),
    color = "#BBBBBC",
    shape = 18,
    size = 3.0
  ) +
  
  geom_segment(
    data = subset(all.lines,
                  Reason.Stop == "Ongoing" &
                  Tx.Type %in% c("cdk", "parp")),
    aes(
      x = End.Date.norm,
      y = index,
      xend = End.Date.norm + 2,
      yend = index
    ),
    arrow = arrow(length = unit(0.2, "cm"))
  ) +
  
  geom_point(
    data = subset(all.lines, Rapid.Prog == 0 & Best.Response == "CR"),
    aes(x = Scan.Date.Norm, y = index),
    color = "#FFFDEC",
    shape = 19,
    size = 3
  ) +
  geom_point(
    data = subset(all.lines, Rapid.Prog == 0 & Best.Response == "PR"),
    aes(x = Scan.Date.Norm, y = index),
    color = "#9cc0cd",
    shape = 19,
    size = 3
  ) +
  geom_point(
    data = subset(all.lines, Rapid.Prog == 0 & Best.Response == "SD"),
    aes(x = Scan.Date.Norm, y = index),
    color = "#6b8590",
    shape = 19,
    size = 3
  ) +
  
  # Tx Line CDK
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & Tx.Line == 1),
    aes(x = -2, y = index),
    fill = "#E2EEF5",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & Tx.Line == 2),
    aes(x = -2, y = index),
    fill = "#8FB9D1",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & Tx.Line > 2),
    aes(x = -2, y = index),
    fill = "#2389AF",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & LOH_status == "AI_LOH_ALT"),
    aes(x = -4, y = index),
    fill = "#DF3E9C",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & LOH_status == "No_LOH"),
    aes(x = -4, y = index),
    fill = "#FAC1E3",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & LOH_status == "Non_evaluable"),
    aes(x = -4, y = index),
    fill = "#FFFFFF",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & CDK == "Palbociclib"),
    aes(x = -6, y = index),
    fill = "#EEDCD6",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & CDK == "Abemaciclib"),
    aes(x = -6, y = index),
    fill = "#D38D7B",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & CDK == "Ribociclib"),
    aes(x = -6, y = index),
    fill = "#955442",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & AI.SERD == "AI"),
    aes(x = -8, y = index),
    fill = "#E9CBF2",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & AI.SERD == "SERD"),
    aes(x = -8, y = index),
    fill = "#BC59D3",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & Interim.Platinum == 1),
    aes(x = -10, y = index),
    fill = "#00B26E",
    color = "black",
    shape = 22,
    size = 4.5
  ) +
  geom_point(
    data = subset(all.lines, Tx.Type == "cdk" & Interim.Platinum == 0),
    aes(x = -10, y = index),
    fill = "#B2E1C4",
    color = "black",
    shape = 22,
    size = 4.5
  ) + 
  theme(axis.text.y = element_blank(), 
        axis.line.y = element_blank(), 
        axis.ticks = element_blank()) + 
  ylab("") + 
  xlab("Time (months)")

alc <- all.lines %>% select(index, Tx.Type, Tx.Line, deidentified_time, event, Reason.Stop) %>% rename(time = deidentified_time)
alc <- alc %>% filter(Tx.Type %in% c("cdk", "parp"))

alc <- distinct(alc)
alc <- alc %>% mutate(event = case_when(is.na(event)~ 0, TRUE ~ event))

lines.cdk.parp <- coxph(Surv(time,event) ~ Tx.Type + strata(index), data= alc)
summary(lines.cdk.parp)

rc <- all.lines %>% select(index, Tx.Type, Best.Response) %>% rename(response = Best.Response) %>% filter(!is.na(response)) %>% filter(Tx.Type %in% c("cdk", "parp")) %>% filter(response != "No_scan")
rc <- rc %>% mutate(OR = case_when(response %in% c("PR", "CR") ~ 1, TRUE ~ 0))
fisher.exact(table(rc$OR, rc$Tx.Type))
```

```{r pre_post_acquired_B2, include = FALSE, echo = FALSE}
all.pw2.plus <- read.csv("../data/Supp_Fig2g_pre_post_B2_ANON.csv")
all.pw2.plus <- all.pw2.plus %>% select(-X) %>% rename(Patient_Anonymized = Anonymized.ID)

{get_type_fun = function(x) strsplit(x, ";")[[1]]

col_op = c("WT" = "#CCCCCC", "GL" = brewer.pal(6, "BuPu")[6], "SOM" = brewer.pal(6, "BuPu")[3], "gWT" = brewer.pal(6, "BuPu")[1],
          "Missense_driver" =  "#005000", "Splice_driver" = "#EE7600", "Truncating_driver" = "#000000", 
          "Fusion" = "purple", 
          "Amplification" = "red", "Deletion" = "blue")


alter_fun = list(
    background = function(x,y,w,h) {grid.rect(x,y,w,h, gp = gpar(fill = "white", col = NA))}, 
   gWT = function(x, y, w, h) {
    grid.rect(x, y, w-unit(2, "pt"), h-unit(2, "pt"),
              gp = gpar(fill = col_op["gWT"], col = NA))
   },
   GL = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
              gp = gpar(fill = col_op["GL"], col = NA))
   },
   SOM= function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
              gp = gpar(fill = col_op["SOM"], col = NA))
   },
   Amplification = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
              gp = gpar(fill = col_op["Amplification"], col = NA))
   },
    Deletion = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
              gp = gpar(fill = col_op["Deletion"], col = NA))
   },
   Missense_driver = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.33,
              gp = gpar(fill = col_op["Missense_driver"], col = NA))
   },
   Splice_driver = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.33,
              gp = gpar(fill = col_op["Splice_driver"], col = NA))
   },
   Truncating_driver = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.33,
              gp = gpar(fill = col_op["Truncating_driver"], col = NA))
   },
   Fusion = function(x, y, w, h) {
     grid.rect(x, y, w-unit(2, "pt"), h*0.33,
              gp = gpar(fill = col_op["Fusion"], col = NA))
  },
   acquired = function(x, y, w, h) {
    grid.rect(x, y, w, h,
              gp = gpar(fill = NA, lwd = 2))
   },
   Not_Tested = function(x,y,w,h) {
     grid.points(x,y,pch = "-")
   },
     WT = function(x, y, w, h) {
    grid.rect(x, y, w*0.9, h*0.9,
              gp = gpar(fill = col_op["WT"], col = NA))
   }
  
    )
  

heatmap_legend_param = list(title = "Variants (Annotated Drivers)", at = c("GL", "SOM", "Missense_driver", "Splice_driver", "Truncating_driver",  
                                                                           # "Fusion", 
                                                                           "Amplification", "Deletion", "acquired"), 
                            labels = c("gBRCA2", "sBRCA2", "Missense mutation (putative driver)", "Splice Site mutation (putative driver)", "Truncating mutation (putative driver)",
                           #"Fusion (putative driver)", 
                          "Amplification", "Homozygous deletion", "Acquired on CDK4/6"), ncol = 3)


all.pw2.plus <- all.pw2.plus %>% 
  mutate(across(Post_RB1:Post_CCNE1, ~factor(.x, levels = c("Not Tested", "WT", "Deletion", "Amplification", "Fusion", "Splice_driver", "Missense_driver", "Truncating_driver", "Amplification;acquired", "Deletion;acquired", "Fusion;acquired", "Splice_driver;acquired", "Missense_driver;acquired", "Truncating_driver;acquired")))) 

all.pw2.plus <- all.pw2.plus %>% mutate(BRCA2 = factor(BRCA2, levels = c("WT", "GL")))

all.pw2.plus <- all.pw2.plus %>%
arrange(-as.numeric(BRCA2),
-as.numeric(Post_RB1), #-as.numeric(Pre_RB1),
-as.numeric(Post_PTEN), #-as.numeric(Pre_PTEN),
-as.numeric(Post_AURKA), #-as.numeric(Pre_AURKA),
-as.numeric(Post_LATS2), #-as.numeric(Pre_LATS2),
-as.numeric(Post_YAP1), #-as.numeric(Pre_YAP1),
-as.numeric(Post_FAT1), #-as.numeric(Pre_FAT1),
-as.numeric(Post_CCNE1))  #-as.numeric(Pre_CCNE1))

awp <- all.pw2.plus %>% select(Patient_Anonymized, BRCA2, Post_RB1, Post_PTEN, Post_AURKA, Post_LATS2, Post_YAP1, Post_FAT1, Post_CCNE1)

abt.plus <- t(awp)
colnames(abt.plus) <- abt.plus[1,]
abt.plus <- abt.plus[-1,]
samp.order <- colnames(abt.plus)

ann.op.plus <- all.pw2.plus %>% pull(BRCA2)
#col.ann <- list(BRCA2 = c("GL" = brewer.pal(6, "BuPu")[6], "SOM" = brewer.pal(6, "BuPu")[3]))

col.ann <- list(BRCA2 = c("GL" = brewer.pal(6, "BuPu")[6], "gWT" = brewer.pal(6, "BuPu")[1]))

ht_opt$COLUMN_ANNO_PADDING = unit(8, "mm")
op_pre_post <- oncoPrint(as.matrix(abt.plus), alter_fun = alter_fun, col = col_op, column_order = samp.order, row_names_side = "left", pct_side = "right", row_names_gp = gpar(fontsize = 12), 
                         
                         column_split = all.pw2.plus$BRCA2, column_gap = unit(6, "mm"),  
                         #row_split = row_cuts, 
                         row_gap = unit(3, "mm"),
                         row_order = row.names(abt.plus),
                        # top_annotation = annot.op, bottom_annotation = annot.bottom,
                         right_annotation = NULL, show_pct = FALSE, 
                         column_title = "Pre-post CDK4/6 samples ", 
                         heatmap_legend_param = heatmap_legend_param,
                         alter_fun_is_vectorized = TRUE)
# pdf(file = "heatmap_attempt_refined_12_17_25.pdf", width = 50, height = 8)
draw(op_pre_post, heatmap_legend_side = "bottom", annotation_legend_side = "bottom")
# dev.off()

b2.pw <- all.pw2.plus %>% filter(BRCA2 == "GL")
wt.pw <- all.pw2.plus %>% filter(BRCA2 == "WT")
b2.acq <- length(grep("acquired", b2.pw$Post_RB1))
wt.acq <- length(grep("acquired", wt.pw$Post_RB1))
fisher.exact(matrix(c(b2.acq , dim(b2.pw)[1] - b2.acq, wt.acq , dim(wt.pw)[1] - wt.acq), nrow = 2))

}
```
